// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuTSFRpwoq2j0FR97onZkqpdlHbbEPYSY',
    appId: '1:856727134895:ios:1e14f564722513c8e6aa5a',
    messagingSenderId: '856727134895',
    projectId: 'innovexa63-mailer',
    storageBucket: 'innovexa63-mailer.firebasestorage.app',
    iosBundleId: 'com.example.premiumMailer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC24XvgGRsQhAA6z7fHrxnvaHe4Q1EDD78',
    appId: '1:856727134895:web:51c43fb024eff78fe6aa5a',
    messagingSenderId: '856727134895',
    projectId: 'innovexa63-mailer',
    authDomain: 'innovexa63-mailer.firebaseapp.com',
    storageBucket: 'innovexa63-mailer.firebasestorage.app',
    measurementId: 'G-NTY1XX8HTL',
  );
}
